-- Daily-question prompts are now generated by Google Gemini instead of OpenAI. Widen the
-- prompt_source domain to accept 'gemini' alongside the existing values. This is purely
-- additive: existing 'openai'/'memory' rows stay valid, so no data backfill is required.

alter table public.game_rounds
  drop constraint if exists game_rounds_prompt_source_check;

alter table public.game_rounds
  add constraint game_rounds_prompt_source_check
  check (prompt_source in ('openai', 'memory', 'gemini'));

-- Re-create the round-creation RPC so generated rounds may declare 'gemini' as their
-- source. The body is otherwise identical to the existing definition; only the accepted
-- prompt_source set changes from {'openai'} to {'openai', 'gemini'}. ('memory'-sourced
-- rounds are created by their own dedicated RPCs, not this one.)
create or replace function public.ensure_daily_question_round(
  target_mode public.game_mode,
  target_round_date date,
  prompt_locale text,
  prompt_text text,
  prompt_source text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  ensured_round_id uuid;
  target_couple_id uuid;
begin
  if auth.uid() is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if target_mode <> 'daily_question' then
    raise exception 'UNSUPPORTED_GAME_MODE';
  end if;

  if prompt_locale not in ('en', 'vi') then
    raise exception 'INVALID_PROMPT_LOCALE';
  end if;

  if coalesce(char_length(btrim(prompt_text)), 0) = 0
    or char_length(prompt_text) > 240 then
    raise exception 'INVALID_PROMPT_TEXT';
  end if;

  if coalesce(btrim(prompt_source), '') not in ('openai', 'gemini') then
    raise exception 'INVALID_PROMPT_SOURCE';
  end if;

  select membership.couple_id
  into target_couple_id
  from public.couple_memberships membership
  where membership.user_id = auth.uid()
    and membership.status = 'active'
  limit 1;

  if target_couple_id is null then
    raise exception 'COUPLE_CONTEXT_REQUIRED';
  end if;

  insert into public.game_rounds (
    couple_id,
    mode,
    round_date,
    prompt_locale,
    prompt_source,
    prompt_text
  )
  values (
    target_couple_id,
    target_mode,
    target_round_date,
    prompt_locale,
    prompt_source,
    btrim(prompt_text)
  )
  on conflict (couple_id, mode, round_date) do nothing
  returning id into ensured_round_id;

  if ensured_round_id is not null then
    return ensured_round_id;
  end if;

  select game_round.id
  into ensured_round_id
  from public.game_rounds game_round
  where game_round.couple_id = target_couple_id
    and game_round.mode = target_mode
    and game_round.round_date = target_round_date
  limit 1;

  if ensured_round_id is null then
    raise exception 'GAME_ROUND_UNAVAILABLE';
  end if;

  return ensured_round_id;
end;
$$;

-- Re-affirm least privilege after replacing the function: only authenticated users may call it.
revoke all on function public.ensure_daily_question_round(public.game_mode, date, text, text, text)
  from public, anon, authenticated, service_role;
grant execute on function public.ensure_daily_question_round(public.game_mode, date, text, text, text)
  to authenticated;
